/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.ProdutoDAO;
import java.awt.Color;
import java.awt.Component;
import java.util.EventObject;
import java.util.List;
import javafx.scene.control.TableCell;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.CellEditorListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import model.Produto;

/**
 *
 * @author 181710180
 */
public class ListProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListProdutos
     */
    private JDesktopPane jdpTelaInicial;
    public ListProdutos(JDesktopPane jdpTelaInicial) {
        initComponents();
        carregarTabela();
        this.jdpTelaInicial = jdpTelaInicial;
    }
private void carregarTabela(){
    String[] colunas = {"Código","Nome","Lote","Categoria","Quantidade",
        "Validade","Fabricação", "Situação"
 };
    List<Produto>listaDeProdutos = ProdutoDAO.getProdutos();
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.setColumnIdentifiers(colunas);
    for(Produto prod:listaDeProdutos){
        
    
        String situacao = "";
        if (prod.getQuantidade()<=3){
            situacao = "Baixo Estoque";
        }
        
        Object[] obj={
        prod.getCodigo(),
        prod.getNome(),
        prod.getLote(),
        prod.getCategoria().getNome(),
        prod.getQuantidade(),
        prod.getValidade(),
        prod.getFabricacao(),
        situacao
                
        };
        
        
        if (prod.getQuantidade()<= 3){
         //   tabelaProdutos.getSelectedRow(setBackground(Color.red));
        
        }
          modelo.addRow(obj);
        
    } 
      
    
      
    
    
    tabelaProdutos.setModel(modelo);
    
    
    
    
            
            
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        btnDarBaixa = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaProdutos.setPreferredSize(new java.awt.Dimension(800, 600));
        jScrollPane2.setViewportView(tabelaProdutos);

        btnDarBaixa.setText("Dar Baixa");
        btnDarBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBaixaActionPerformed(evt);
            }
        });

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDarBaixa)
                    .addComponent(btnAdd))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnDarBaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDarBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBaixaActionPerformed

        int linha = tabelaProdutos.getSelectedRow();
        if (linha == -1){
            
        }else{
            int codigo = (int)tabelaProdutos.getValueAt(linha, 0);
        
        
        DarBaixa db= new DarBaixa(codigo);
        jdpTelaInicial.add(db);
        db.setVisible(true);
        
        }

    }//GEN-LAST:event_btnDarBaixaActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    
        int linha = tabelaProdutos.getSelectedRow();
        if (linha == -1){
            
        }else{
   int codigo = (int)tabelaProdutos.getValueAt(linha, 0);
           
   
   
   Adicionar add = new Adicionar(codigo);
            
            
            
        }  
            
    }//GEN-LAST:event_btnAddActionPerformed
        

    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDarBaixa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
